parameters:
    dailymotion_api_key: 6e6a0bed18211400adf7
    dailymotion_api_secret: 4973b96c068de80195a2cb644437217f4959a529
    dailymotion_username: lesvraisinconnus
    dailymotion_password: bangme24
