parameters:
    dailymotion_api_key: aa81289b98515cba1e93
    dailymotion_api_secret: 2a68d63f959846fd17dc4ae689b685d6804b41e3
    dailymotion_username: lesvraisinconnus
    dailymotion_password: bangme24
