SkreenHouseFactorylesVraisInconnusBundle_homepage:
    pattern:  /
    defaults: { _controller: SkreenHouseFactorylesVraisInconnusBundle:Default:index }

SkreenHouseFactorylesVraisInconnusBundle_done:
    pattern:  /done
    defaults: { _controller: SkreenHouseFactorylesVraisInconnusBundle:Default:done }
